FROM sbtscala/scala-sbt:eclipse-temurin-jammy-21_35_1.9.6_3.3.1 AS build

WORKDIR /app
COPY ./ /app

RUN sbt clean ObserverService/assembly

FROM alpine/java:21-jdk AS run

WORKDIR /app

COPY --from=build /app/ObserverService/target/scala-3.3.1/observer-assembly-0.1.0-SNAPSHOT.jar /app/observer.jar

EXPOSE 8080
CMD [ "java", "-jar", "/app/observer.jar", "0.0.0.0", "host.docker.internal" ]

