FROM sbtscala/scala-sbt:eclipse-temurin-jammy-21_35_1.9.6_3.3.1 AS build

WORKDIR /app
COPY ./ /app

RUN sbt clean minesweeper/assembly

FROM alpine/java:21-jdk AS run

WORKDIR /app

COPY --from=build /app/minesweeper/target/scala-3.3.1/minesweeper-assembly-0.1.0-SNAPSHOT.jar /app/minesweeper.jar

EXPOSE 8080
CMD [ "java", "-jar", "/app/minesweeper.jar", "0.0.0.0", "observer" ]
